[phases.setup]
nixPkgs = ["python310", "gcc", "python310Packages.virtualenv"]

[phases.build]
cmds = ["python -m venv /opt/venv", "source /opt/venv/bin/activate", "pip install -r requirements.txt"]

[phases.start]
cmds = ["uvicorn main:app --host 0.0.0.0 --port $PORT"]
